version: "2"
linters:
  default: all
  enable:
    - bodyclose
    - copyloopvar
    - decorder
    - errcheck
    - errname
    - forbidigo
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - nestif
    - nlreturn
    - perfsprint
    - predeclared
    - staticcheck
    - testifylint
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    generated: lax
    paths:
      - ./gen
      - ./pkg/report
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/ChargePi/chargeflow
  enable:
    - gofmt
    - goimports
