# GoReleaser configuration file
version: 2

# General settings
project_name: chargeflow
builds:
  - id: cli
    main: ./main.go
    binary: chargeflow
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - id: cli-archive
    format: tar.gz
    files:
      - LICENSE.md
      - README.md

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/chargeflow:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/chargeflow:latest"
    dockerfile: ./build/Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: ${{ .Env.GITHUB_REPOSITORY_OWNER }}
    name: chargeflow

changelog:
  sort: asc
  filters:
    exclude:
      - '**/*.md'

