dir: gen/mocks/{{.InterfaceDirRelative}}
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "mock_{{.SrcPackageName|snakecase}}"
filename: "{{.InterfaceName|snakecase}}_mock.go"
formatter: goimports
template: testify
packages:
  github.com/ChargePi/chargeflow/pkg/schema_registry:
    config:
      all: true
