name: "Pull Request Terraform Plan"
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - '.vscode/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - 'scripts/**'
      - 'assets/**'
      - '*.md'

jobs:
  terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.3

      - name: Configure AWS Credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Staging Plan
        id: plan-staging
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ./environment/staging/
        env:
          TF_WORKSPACE: staging
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_cloudflare_email: ${{ secrets.CLOUDFLARE_EMAIL}}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}

      - name: Terraform Prod Plan
        id: plan-prod
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ./environment/production/
        env:
          TF_WORKSPACE: production
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}


      - uses: actions/github-script@v7
        env:
          PLAN_STAGING: "terraform\n${{ steps.plan-staging.outputs.stdout }}"
          PLAN_PROD: "terraform\n${{ steps.plan-prod.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Output for terraform 🔒
            #### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖 ${{ steps.validate.outputs.stdout }}
            #### Terraform Staging Plan 📖 \`${{ steps.plan-staging.outcome }}\`
            #### Terraform Prod Plan 📖 \`${{ steps.plan-prod.outcome }}\`

            <details><summary>Show Staging Plan</summary>

            \`\`\`\n
            ${process.env.PLAN_STAGING}
            \`\`\`

            </details>

            <details><summary>Show Prod Plan</summary>

            \`\`\`
            ${process.env.PLAN_PROD}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Staging Plan Status
        if: steps.plan-staging.outcome == 'failure'
        run: exit 1

      - name: Terraform Prod Plan Status
        if: steps.plan-prod.outcome == 'failure'
        run: exit 1